#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChatMVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bds240792229_db")]
	public partial class HualitongDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertusers(users instance);
    partial void Updateusers(users instance);
    partial void Deleteusers(users instance);
    partial void Insertpwds(pwds instance);
    partial void Updatepwds(pwds instance);
    partial void Deletepwds(pwds instance);
    partial void Insertnames(names instance);
    partial void Updatenames(names instance);
    partial void Deletenames(names instance);
    #endregion
		
		public HualitongDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bds240792229_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HualitongDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HualitongDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HualitongDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HualitongDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
		
		public System.Data.Linq.Table<pwds> pwds
		{
			get
			{
				return this.GetTable<pwds>();
			}
		}
		
		public System.Data.Linq.Table<names> names
		{
			get
			{
				return this.GetTable<names>();
			}
		}
		
		public System.Data.Linq.Table<view_wechatpwds> view_wechatpwds
		{
			get
			{
				return this.GetTable<view_wechatpwds>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="hualitongdb.users")]
	public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _wechat_id;
		
		private System.DateTime _follow_date;
		
		private System.Nullable<int> _pwds_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onwechat_idChanging(string value);
    partial void Onwechat_idChanged();
    partial void Onfollow_dateChanging(System.DateTime value);
    partial void Onfollow_dateChanged();
    partial void Onpwds_idChanging(System.Nullable<int> value);
    partial void Onpwds_idChanged();
    #endregion
		
		public users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wechat_id", DbType="VarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string wechat_id
		{
			get
			{
				return this._wechat_id;
			}
			set
			{
				if ((this._wechat_id != value))
				{
					this.Onwechat_idChanging(value);
					this.SendPropertyChanging();
					this._wechat_id = value;
					this.SendPropertyChanged("wechat_id");
					this.Onwechat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_follow_date", DbType="DateTime NOT NULL", IsDbGenerated = true)]
		public System.DateTime follow_date
		{
			get
			{
				return this._follow_date;
			}
			set
			{
				if ((this._follow_date != value))
				{
					this.Onfollow_dateChanging(value);
					this.SendPropertyChanging();
					this._follow_date = value;
					this.SendPropertyChanged("follow_date");
					this.Onfollow_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwds_id", DbType="Int")]
		public System.Nullable<int> pwds_id
		{
			get
			{
				return this._pwds_id;
			}
			set
			{
				if ((this._pwds_id != value))
				{
					this.Onpwds_idChanging(value);
					this.SendPropertyChanging();
					this._pwds_id = value;
					this.SendPropertyChanged("pwds_id");
					this.Onpwds_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="hualitongdb.pwds")]
	public partial class pwds : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pwds_id;
		
		private string _student_num;
		
		private string _urp_pwd;
		
		private string _jw_pwd;
		
		private string _ty_pwd;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpwds_idChanging(int value);
    partial void Onpwds_idChanged();
    partial void Onstudent_numChanging(string value);
    partial void Onstudent_numChanged();
    partial void Onurp_pwdChanging(string value);
    partial void Onurp_pwdChanged();
    partial void Onjw_pwdChanging(string value);
    partial void Onjw_pwdChanged();
    partial void Onty_pwdChanging(string value);
    partial void Onty_pwdChanged();
    #endregion
		
		public pwds()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwds_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pwds_id
		{
			get
			{
				return this._pwds_id;
			}
			set
			{
				if ((this._pwds_id != value))
				{
					this.Onpwds_idChanging(value);
					this.SendPropertyChanging();
					this._pwds_id = value;
					this.SendPropertyChanged("pwds_id");
					this.Onpwds_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_num", DbType="VarChar(10)")]
		public string student_num
		{
			get
			{
				return this._student_num;
			}
			set
			{
				if ((this._student_num != value))
				{
					this.Onstudent_numChanging(value);
					this.SendPropertyChanging();
					this._student_num = value;
					this.SendPropertyChanged("student_num");
					this.Onstudent_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urp_pwd", DbType="VarChar(11)")]
		public string urp_pwd
		{
			get
			{
				return this._urp_pwd;
			}
			set
			{
				if ((this._urp_pwd != value))
				{
					this.Onurp_pwdChanging(value);
					this.SendPropertyChanging();
					this._urp_pwd = value;
					this.SendPropertyChanged("urp_pwd");
					this.Onurp_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jw_pwd", DbType="VarChar(11)")]
		public string jw_pwd
		{
			get
			{
				return this._jw_pwd;
			}
			set
			{
				if ((this._jw_pwd != value))
				{
					this.Onjw_pwdChanging(value);
					this.SendPropertyChanging();
					this._jw_pwd = value;
					this.SendPropertyChanged("jw_pwd");
					this.Onjw_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ty_pwd", DbType="VarChar(11)")]
		public string ty_pwd
		{
			get
			{
				return this._ty_pwd;
			}
			set
			{
				if ((this._ty_pwd != value))
				{
					this.Onty_pwdChanging(value);
					this.SendPropertyChanging();
					this._ty_pwd = value;
					this.SendPropertyChanged("ty_pwd");
					this.Onty_pwdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="hualitongdb.names")]
	public partial class names : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _student_num;
		
		private string _student_name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstudent_numChanging(string value);
    partial void Onstudent_numChanged();
    partial void Onstudent_nameChanging(string value);
    partial void Onstudent_nameChanged();
    #endregion
		
		public names()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_num", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string student_num
		{
			get
			{
				return this._student_num;
			}
			set
			{
				if ((this._student_num != value))
				{
					this.Onstudent_numChanging(value);
					this.SendPropertyChanging();
					this._student_num = value;
					this.SendPropertyChanged("student_num");
					this.Onstudent_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_name", DbType="VarChar(10)")]
		public string student_name
		{
			get
			{
				return this._student_name;
			}
			set
			{
				if ((this._student_name != value))
				{
					this.Onstudent_nameChanging(value);
					this.SendPropertyChanging();
					this._student_name = value;
					this.SendPropertyChanged("student_name");
					this.Onstudent_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="hualitongdb.view_wechatpwds")]
	public partial class view_wechatpwds
	{
		
		private string _wechat_id;
		
		private string _student_num;
		
		private string _urp_pwd;
		
		private string _ty_pwd;
		
		private string _jw_pwd;
		
		public view_wechatpwds()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wechat_id", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string wechat_id
		{
			get
			{
				return this._wechat_id;
			}
			set
			{
				if ((this._wechat_id != value))
				{
					this._wechat_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_num", DbType="VarChar(10)")]
		public string student_num
		{
			get
			{
				return this._student_num;
			}
			set
			{
				if ((this._student_num != value))
				{
					this._student_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urp_pwd", DbType="VarChar(11)")]
		public string urp_pwd
		{
			get
			{
				return this._urp_pwd;
			}
			set
			{
				if ((this._urp_pwd != value))
				{
					this._urp_pwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ty_pwd", DbType="VarChar(11)")]
		public string ty_pwd
		{
			get
			{
				return this._ty_pwd;
			}
			set
			{
				if ((this._ty_pwd != value))
				{
					this._ty_pwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jw_pwd", DbType="VarChar(11)")]
		public string jw_pwd
		{
			get
			{
				return this._jw_pwd;
			}
			set
			{
				if ((this._jw_pwd != value))
				{
					this._jw_pwd = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
